version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      - mongodb